default: dev

environment:
  def:
    base_url: ''
    auth_token: ''
    timeout: 5
  staging:
    base_url: ''
    auth_token: ''
    timeout: 10
  prod:
    base_url: ''
    auth_token: ''
    timeout: 10